version: '3.8'

services:
  backend:
    build: .
    container_name: knowledge-garden-backend
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    environment:
      - NODE_ENV=production 